### ISSUE TITLE
Create a maps config file that associates data with maps

### ISSUE THREAD

**Issue by WyndevCodes** [WyndevCodes/Minestom-Tower-Defense#19]
YML file format:
```yaml
maps:
  1:
    map-name: 'Tower Map'
    map-creators:
      - 'The Hypixel Team'
    map-schematic: 'schematic.schem'
    type: SOLO # 1 player per team (other options are DUO (2 per team) or TEAM (2 teams of 4))
    # Then somehow define region data, such as spawn location and tower track boundaries for each team
```
